### ISSUE TITLE
Form will only display on frontend when logged into Craft

### ISSUE THREAD

**Issue by richcoopa** [Dolphiq/craft3-forms#19]
When not logged in I get these errors in the web.log

`2019-08-02 16:33:40 [-][-][sj31j2rp047pv2nolbphmr2i2c][info][nystudio107\retour\Retour::init] Retour plugin loaded
2019-08-02 16:33:40 [-][-][sj31j2rp047pv2nolbphmr2i2c][info][yii\web\Session::open] Session started
2019-08-02 16:33:40 [-][-][sj31j2rp047pv2nolbphmr2i2c][trace][craft\web\Application::_processActionRequest] Route requested: 'dolphiq-craft3-forms/main/index'
2019-08-02 16:33:40 [-][-][sj31j2rp047pv2nolbphmr2i2c][trace][yii\base\Controller::runAction] Route to run: dolphiq-craft3-forms/main/index
2019-08-02 16:33:40 [-][-][sj31j2rp047pv2nolbphmr2i2c][trace][nystudio107\retour\{closure}] ErrorHandler::EVENT_BEFORE_HANDLE_EXCEPTION
2019-08-02 16:33:40 [-][-][sj31j2rp047pv2nolbphmr2i2c][error][yii\web\HttpException:503] craft\web\ServiceUnavailableHttpException in /Users/myusername/Websites/websitename/vendor
/craftcms/cms/src/web/Controller.php:163
Stack trace:
#0 /Users/myusername/Websites/websitename/vendor/yiisoft/yii2/base/Controller.php(155): craft\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /Users/myusername/Websites/websitename/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('index', Array)
#2 /Users/myusername/Websites/websitename/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#3 /Users/myusername/Websites/websitename/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('dolphiq-craft3-...', Array)
#4 /Users/myusername/Websites/websitename/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('dolphiq-craft3-...', Array)
#5 /Users/myusername/Websites/websitename/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#6 /Users/myusername/Websites/websitename/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#7 /Users/myusername/Websites/websitename/web/index.php(21): yii\base\Application->run()
#8 {main}
2019-08-02 16:33:40 [-][-][sj31j2rp047pv2nolbphmr2i2c][info][application] $_GET = [
    'p' => 'actions/dolphiq-craft3-forms/main/index'
    'handle' => 'contact'
    'params' => '[]'
    '_' => '1564760020481'
]`

Forms directory:
[forms.zip](https://github.com/Dolphiq/craft3-forms/files/3461942/forms.zip)

The twig template simply has:
`{{ dolphiqForm('contact') }}`

Craft CMS 3.2.8
Latest plugins installed (just `composer update`d)

Any idea?

**Comment by richcoopa** [comment]
Okay I have managed to resolve the issue by making a code change. On your MainController line 40:
`    protected $allowAnonymous = 1;`
rather than `true`

**Comment by richcoopa** [comment]
Actually this would be better:
`    protected $allowAnonymous = self::ALLOW_ANONYMOUS_LIVE;`
Can you apply the code change to the repo?
